### ISSUE TITLE
RFC: Windows support

### ISSUE THREAD

**Issue by eric-burel** [VulcanJS/vulcan-next#135]
**Describe the problem you want to solve or enhancement you want to bring**

Support WIndows as much as possible. This is an umbrella issue for all trouble you can encounter when installing Vulcan Next on Windows.

Current issues:

- $(pwd) (current directory) command is not working when running Mongo with Docker
- Actually, I am not even sure you can dockerize Mongo on Windows

**Questions to the community**

I am not coding on Windows at all so any help from the community is more than welcome!

**Comment by eric-burel** [comment]
A user reported issues with Cypress, namely the environment loading function not working properly (we have a Cypress plugin that lruns Next.js "loadEnv" logic) in Visual Studio environment.

**Comment by daniablank** [comment]
Additionally, when running `yarn run dev:test`, whether in Visual Studio or not, this stack trace appears.

```
(node:20144) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, realpath 'C:\Users\dania\Documents\GitHub\Voting-And-Stamps\#'
    at Function.realpathSync.native (fs.js:1855:3)
    at Object.getProjectDir (C:\Users\redacted\Documents\GitHub\Voting-And-Stamps\node_modules\next\dist\lib\get-project-dir.js:39:46)
    at nextDev (C:\Users\redacted\Documents\GitHub\Voting-And-Stamps\node_modules\next\dist\cli\next-dev.js:84:37)
    at C:\Users\redacted\Documents\GitHub\Voting-And-Stamps\node_modules\next\dist\bin\next:119:34
    ```
    
    When I use `yarn run dev` instead and run a barebones Cypress test, I get this error:
    
    ```
    expected { Object (errors, data) } to have property 'length'
cypress/integration/integration/example.spec.js:19:1
  17 |         // https://on.cypress.io/assertions
  18 |         expect(response).property('status').to.equal(200)
> 19 |         expect(response).property('body').to.have.length(500)
     | ^
  20 |         expect(response).to.include.keys('headers', 'duration')
  21 |         })
  22 |     })
  ```
